### ISSUE TITLE
Use Csharp Repl in other software

### ISSUE THREAD

**Issue by chuongmep** [waf/CSharpRepl#100]
### Feature Description

Dear @waf 
I working with project open source in below but it working with python shell , 
https://github.com/chuongmep/CadPythonShell
I have a question, whether we can apply this project to build and upgrade **CadPythonShell** to support platform **C# Shell** or not.This project is only in net 4.8 and cannot go higher because the main software dependency they are working on is autocad
I would like to describe it in a little detail. They run in wpf and as a plugin inside an autocad. Any suggestions are greatly appreciated.
My research direction is to use https://github.com/roslynpad/roslynpad to do but I find they have too many bug in libraries, hope to get some advice from you.

**Comment by kindermannhubert** [comment]
CSharpRepl targets .NET 6.0 so you can't use it from .NET Framework. It could be used as an external (.NET 5) process communicating with another (.NET Framework) process via some IPC. This was already discussed in #57.

**Comment by chuongmep** [comment]
Yes, but it my problem is .NET Framework load a dll of .NET6, example I create a .NET framework and load CSharpRepl targets .NET 6.0, you can see my problem.
![image](https://user-images.githubusercontent.com/31106432/159104817-209ef289-9bff-4523-bba4-9c57cc46aa1e.png)

**Comment by waf** [comment]
Unfortunately csharprepl (and other .NET 6 projects) can't be loaded in .NET Framework 4.8. I suspect CadPythonShell is working for you because it [also targets .NET Framework 4.8](https://github.com/chuongmep/CadPythonShell/blob/580e1729d1b7d8d0f8ec539f4b2c46d3e19d2a8f/CADPythonShell/CADPythonShell.csproj#L3).

Depending on your goal, the simplest way might be to use the Roslyn Scripting APIs directly, by following this guide: https://github.com/dotnet/roslyn/blob/main/docs/wiki/Scripting-API-Samples.md -- these APIs target .NET Standard 2.0 which works on .NET Framework 4.8.

**Comment by chuongmep** [comment]
hmm, actually i also want my tool to be able to run on .NET6, but it's just a plugin and it works inside **Autocad** , and **Autocad** doesn't support .NET6 yet. So if you have any idea about allowing to experience both .net framework and .net 6 inside your code, that I think is necessary.

**Comment by waf** [comment]
Yep, I'd recommend using a .NET Standard 2.0 library for that, namely the Roslyn Scripting APIs I linked above. We won't be doing that for CSharpRepl, though, as .NET Framework 4.8 compatibility is not a goal.

**Comment by chuongmep** [comment]
Thanks for pointing out the problems, i will take note and try with .NET Standard 2.0
