### ISSUE TITLE
intellisense area is hidden

### ISSUE THREAD

**Issue by HAndy2013** [waf/CSharpRepl#11]
hello, this project is pretty cool. 🤩

when type in the bottom of terminal, intellisense area is hidden 👇
![image](https://user-images.githubusercontent.com/3422711/121112668-4c18f480-c843-11eb-9d03-55b59ea48825.png)

**Comment by waf** [comment]
Thanks! This is actually fixed, just pending a release. I'll keep this issue open until I can publish the release (a few days out as I sort through some other issues).

It was fixed in the underlying prompt library here: https://github.com/waf/PrettyPrompt/issues/6 , once I pull in that updated dependency it will be resolved.

**Comment by waf** [comment]
This fix has been published. You can get it in the [new version of csharprepl](https://www.nuget.org/packages/CSharpRepl/0.2.3) (0.2.3) that includes this change. You can update via `dotnet tool update -g csharprepl` (it can sometimes take some minutes for the package to be fully available for download).

Credit goes to @realivanjx for fixing it 🚀
