### ISSUE TITLE
Passing argument to .csx file

### ISSUE THREAD

**Issue by realivanjx** [waf/CSharpRepl#12]
How to pass command line arguments to `csx` file. With `dotnet-script` I can do `dotnet-script myfile.csx -- arg1 arg2`. Is this supported in csharprepl? Thanks.

**Comment by waf** [comment]
Thanks for opening this. It's not supported currently. csharprepl treats csx files more as init scripts for the current REPL session, i.e. a place that sets up common references, imports, etc. that would then be used interactively in the REPL session.

dotnet-script is much more advanced in this regard, and honestly I'd recommend using dotnet-script instead of csharprepl for general csx script execution. That's really the main use case for dotnet-script. Both these projects target different, although overlapping, areas.

That being said, I'm not against adding argument-passing capabilities to csharprepl, just with the acknowledgement that dotnet-script will probably always be a more full-featured C# script executor, and that's OK 😄

**Comment by waf** [comment]
Also, if you do have a use case where passing arguments would help you with "init script" style csx files, I'd love to hear more about it, it's not a workflow I'm familiar with.

**Comment by realivanjx** [comment]
I think a lot of people will expect this to have arguments passing feature too especially coming from dotnet-script. Also dotnet run supports argument passing too. I think i can still work this around by using environment variable but it will be much more convenient to be able to pass arguments directly. Just my opinion.

**Comment by waf** [comment]
Thinking through this. If we do end up implementing this, it seems like a global `string[] args` would be the way to go. 

- Make it available when evaluating csx files
- Should also be available when using the REPL interactively
 
However, in both the above cases, it should only be available when args are actually supplied at the command line. If they're not supplied, we shouldn't clutter up the global namespace.

**Comment by waf** [comment]
@realivanjx if you'd like, you can check out the functionality in PR #15 which adds support for passing arguments to .csx files. It should work for your use case. I'll be testing it out over the next few days. Thanks!

**Comment by waf** [comment]
This is now released in version 0.2.6. You can update via: 

```
dotnet tool update -g csharprepl
```

**Comment by waf** [comment]
Thanks for your input and feedback on the PR! I've added you to the CONTRIBUTORS.md

https://github.com/waf/CSharpRepl/commit/beaa046c116ec4a89736c494f505873a34bf681f

Cheers!
