### ISSUE TITLE
Add exception callstacks highlighting

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#196]
### Feature Description

 instead of all red text

**Comment by kindermannhubert** [comment]
I have the first version. 
@waf could you have a look at the screenshots and say what you think? I'm not sure about new '---- EXCEPTION ----' header and the inconsistency of detailed vs non-detailed output.

Before:
![image](https://user-images.githubusercontent.com/11704036/202917680-b2793abb-ffbb-4e7b-9412-50943a148c53.png)

After (detailed output):
![image](https://user-images.githubusercontent.com/11704036/202917535-d692eddd-1b95-4bc6-bfbc-99565bf0f8b6.png)


Before and after (non-detailed output; without change):
![image](https://user-images.githubusercontent.com/11704036/202917458-fb131949-f20c-4dee-b5de-ed2d80aaca3c.png)

**Comment by waf** [comment]
Nice, those stack traces are looking good! I think we need to make the exception "stand out" from the surrounding code as it can kind of blur together after syntax highlighting (which I think you're solving with the header/footer).

How about if we tried to set it off with vertical markers rather than horizontal? Something like this (please excuse the poor image editing mockup quality!):

![image](https://user-images.githubusercontent.com/97195/203070808-0ce2872e-f1d5-4c04-bcce-271cf15ad1c3.png)

It doesn't have to be the word `[Error]`, something like `[ERR]` or the pipe character or box drawing characters would be fine too.

As an aside, somewhere along the way did we lose the (row, column) position in the exception? That's nice especially for multi-line statements to point out where the problem is:

![image](https://user-images.githubusercontent.com/97195/203066296-5bd60386-6319-445f-bdae-4841f2efa287.png)

**Comment by kindermannhubert** [comment]
Hmm, the prefix approach (e.g. `[ERR]`) quickly becomes ugly when the lines of the call stack are long and they wrap.
We need to wrap the lines manually and somehow indent them.
We could extend, refine and make public some PrettyPrompt bits (there already is text wrapping and box drawing) and we could put the exception inside a red box with "Exception" title.

**Comment by kindermannhubert** [comment]
@waf What do you think about the usage of Spectre.Console in CSharpRepl? Only for some outputs. It could be used for more advanced outputs (exceptions in boxes, tables of IEnumerable results, maybe some interactive output object browsing, ...). It would be easier than reimplementing everything in PrettyPrompt.

**Comment by waf** [comment]
I'm in favor of it. It didn't seem worth using it just for the simple autocompletion box drawing, but if we're adding more complex UI, then let's go for it.

**Comment by kindermannhubert** [comment]
I'm working on Spectre.Console integration in https://github.com/kindermannhubert/CSharpRepl/tree/spectre. Locally I already have reimplemented the current output highlighting with it.
