### ISSUE TITLE
add `help`, `clear` and `exit` to completion

### ISSUE THREAD

**Issue by sorousherafat** [waf/CSharpRepl#262]
### Feature Description

`csharprepl` supports built-in commands like `help`, `clear` and `exit`.
`help` and `clear` are mentioned in the start prompt but some users may not even know that `csharprepl` supports `clear` for clearing the terminal.
on the other hand, adding these three commands to completion will probably result in better user experience.

**Comment by waf** [comment]
Hi, thanks for the issue! I'd rather keep completion to be only valid C# for now, rather than mixing csharprepl commands + C# code in the completion window. But I agree that `clear` is not discoverable at all. Thanks for raising that.

For now, I've helped increase the discoverability of the `clear` command:
![image](https://github.com/waf/CSharpRepl/assets/97195/ebd709cc-0d64-40fd-86b5-e939b97bab92)
