### ISSUE TITLE
Provide way to configure features

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#48]
### Feature Description

Would be nice if csharprepl had some configuration file.

Mainly I'd like to be able to configure key mappings. But there is (or will be) much more thing that could be configurable.

Could be probably done similarly like theme json.

**Comment by waf** [comment]
Yep, I think a configuration file would be good. 

CSharpRepl already supports [Response Files](https://github.com/dotnet/command-line-api/blob/main/docs/Features-overview.md#response-files) which is a form of configuration -- perhaps having the idea of a "default response file" would be a decent way of implementing this.

If we feel that's too esoteric, I'm also fine having a separate config file perhaps similar to the `settings.json` config file that Windows Terminal uses, but it means we'll have some amount of duplication between command line parameters and the config file.

**Comment by kindermannhubert** [comment]
I'm already extending command line arguments and it seems fine to me to use rsp files as config (although never heard of them before 🙂).

I would close this when we prepare the default rsp file.

**Comment by waf** [comment]
I've [pushed a branch](https://github.com/waf/CSharpRepl/tree/add-configuration-file-support) that implements this, but with a failing unit test, due to an issue in the way that System.CommandLine parses rsp files.

The System.CommandLine project just fixed this issue a matter of days ago (see https://github.com/dotnet/command-line-api/issues/1665). I'd like to wait for that fix to be released before releasing this feature, as it makes the response files simpler to use.
