### ISSUE TITLE
VS highlighting theme

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#49]
### Feature Description

Hi,
I'd like to have Visual Studio Dark theme highlighting colors here.
I can prepare this but I'm not sure if you would prefer updating ```DefaultTheme``` (this would be my choice so familiar colors would be used out of the box) or if you would create new theme besides currently existing Dracula theme.

**Comment by waf** [comment]
This is a great idea. There's two suggestions here:

1. Adding a VS dark theme, similar to the currently existing Dracula theme
    -  Yes, this would be good.
1. Whether not we update the DefaultTheme to use the VS dark theme
    - Something to investigate, if a user has customized their terminal to not have a dark background (e.g. they're using Windows Terminal with the built-in `Solarized Light` or `Tango Light` theme) -- would it be legible? A benefit of using the default colors as we currently do is that it should always be legible.
    - If we do have a solution for the above point, we'd also need a way for users to specify that CSharpRepl should follow their terminal color palette. If a user has spent time customizing their color palette, we should support using their colors.

**Comment by kindermannhubert** [comment]
> A benefit of using the default colors as we currently do is that it should always be legible.

I do understand the problem of illegibility when user color customization applies. But it already does not work. It's sufficient that the user has a custom background color set to any of (or similar) color that we use for highlighting and it will be illegible.
For example, this is Solarized Light theme in WinTerminal:
![image](https://user-images.githubusercontent.com/11704036/144828254-cdf79fe4-c906-47d9-8376-247be8a761a0.png)
The ```Now.ToShortDateString()``` part is barely visible.

I'm afraid there is no good way to find out the current (at least) background color of terminal. There's a lot of different terminals and different OSs. Terminal could also run on a different computer.

Personally, I would assume 'dark' terminal as default a be clear at top of ReadMe that we support multiple themes. The next idea I have would be to have some 'help' for example on the last line of the console be always present (could be turned off in settings file) - something like
<pre>
Enter (evaluate)        Shift+Enter (new line)       F2(change theme)       F9 (...)
</pre>
where for example F2 would cycle in available themes.

**Comment by waf** [comment]
> It's sufficient that the user has a custom background color set to any of (or similar) color that we use for highlighting

For what it's worth -- the default theme doesn't set specific colors (i.e. specific RGB codes); but it does set that e.g. C# properties should use whatever color is in the "white slot" of the terminal's color palette. If I look at the Solarized Light theme for Windows Terminal, it defines a white color that is very close to the background color:

```json
"background": "#FDF6E3",
"white": "#EEE8D5",
```

I'd consider that a bug in the Solarized Light theme! However, possibly the existence of this mismatch in Windows Terminal means that not many people are using this light color theme.

Only concern is that currently we don't need to deal with any bug reports about color themes, because we've always delegated control of this to the terminal -- as soon as we start specifying RGB codes, I'm sure we'll have bug reports.

Let's go ahead and make VS dark theme highlighting the default, but we need to ensure that users can easily switch back to a terminal-color-palette theme (the current default). We should release https://github.com/waf/CSharpRepl/issues/48 at the same time so users can configure it once if they want to switch back.

**Comment by kindermannhubert** [comment]
Oh, I didn't realize that ```AnsiColor``` members are not specific colors but just references into "terminal color scheme". Now I understand.
That means I should change the default color of ```selectedCompletionItemBackground``` in https://github.com/waf/PrettyPrompt/pull/25 to some predefined color. Currently used RGB color can be used for example in VS dark theme.

**Comment by kindermannhubert** [comment]
Preview:
![image](https://user-images.githubusercontent.com/11704036/147275943-5b368ea1-9255-4699-a9ac-8b613bd9edcc.png)
